assertion(a_reflect_one, works_at(user,acme)).
assertion_polarity(a_reflect_one, positive).
assertion_modality(a_reflect_one, asserted).
assertion_time(a_reflect_one, unknown).
assertion_source(a_reflect_one, fixture_turn_1).
assertion_confidence(a_reflect_one, 0.9).
assertion(a_reflect_two, works_at(user,acme)).
assertion_polarity(a_reflect_two, positive).
assertion_modality(a_reflect_two, asserted).
assertion_time(a_reflect_two, unknown).
assertion_source(a_reflect_two, fixture_turn_2).
assertion_confidence(a_reflect_two, 0.9).
assertion(a_identity, role(artem,user)).
assertion_polarity(a_identity, positive).
assertion_modality(a_identity, asserted).
assertion_time(a_identity, unknown).
assertion_source(a_identity, fixture_turn_3).
assertion_confidence(a_identity, 1).
