#!/usr/bin/env node
"use strict";
const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const { spawn, spawnSync } = require("node:child_process");
const { WorldAgent } = require("../agent");
const { check } = require("../checker");
const H = require("../paired-biographies/harness.cjs");
const { parseAnswer } = require("../temporal-relational-stress/collector.cjs");
const { CONDITIONS, generateFixture, stable } = require("./generator.cjs");
const ROOT = path.resolve(__dirname, "../..");
const DEFAULT_FIXTURE = path.join(ROOT, ".cdr/waves/autonomous-prolog-tool-v5/fixture.json");
const EXPECTED_FIXTURE_SHA256 = "3fcfa8dedc54a8bd09643143a3e94237a535a9b38e380f6beab161d1f9826269";
const SYSTEM = "Solve one finite signed-Horn task. Use only the supplied snapshot and exposed tools. Never invent facts. Return only the requested JSON object.";
const sha256 = value => crypto.createHash("sha256").update(value).digest("hex");
const exactWrite = (file, value) => { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`); };
const supports = (result, query) => { const sets = literal => result.raw_support_sets.filter(x => x.literal === literal).map(x => [...x.item_ids].sort()).sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b))); return { positive_support_sets: sets(query), negative_support_sets: sets(`neg(${query})`) }; };

async function loadFrozenFixture(file = DEFAULT_FIXTURE) {
  const resolved = path.resolve(file), bytes = fs.readFileSync(resolved, "utf8"); if (sha256(bytes) !== EXPECTED_FIXTURE_SHA256) throw new Error("fixture hash mismatch"); if (stable(generateFixture()) !== bytes) throw new Error("fixture regeneration mismatch"); return { file: resolved, sha256: EXPECTED_FIXTURE_SHA256, fixture: JSON.parse(bytes) };
}
async function seedWorld(item, directory) {
  const world = path.join(directory, "world"); const agent = new WorldAgent(world, { agent_id: item.case_id, ideas: item.formal_world.ideas, startTime: 0 });
  const source = agent.observe("Frozen synthetic final active snapshot.", { at: 0, sourceGroup: `${item.case_id}_fixture`, sourceGroupAttestation: { by: "autonomous-prolog-tool-v5", reason: "frozen synthetic fixture", lineage_id: `${item.case_id}_fixture` } });
  const proposal = agent.propose(source, item.formal_world.active_items.map(({ id, program }) => ({ id, program })), { at: 0 }); await agent.admit(proposal, { admit: true, by: "autonomous-prolog-tool-v5", reason: "frozen synthetic fixture" });
  const result = await check({ snapshot: agent.snapshot(), query: item.formal_world.query }); if (result.status !== "ok" || result.raw_status !== item.oracle.status) throw new Error(`${item.case_id}: seeded checker mismatch`); const proof = supports(result, item.formal_world.query); if (JSON.stringify(proof.positive_support_sets) !== JSON.stringify(item.oracle.positive_support_sets) || JSON.stringify(proof.negative_support_sets) !== JSON.stringify(item.oracle.negative_support_sets)) throw new Error(`${item.case_id}: seeded support mismatch`);
  const ideasPath = path.join(directory, "ideas.json"); exactWrite(ideasPath, item.formal_world.ideas); return { directory: world, snapshot_sha256: agent.snapshot().sha256, ideas_path: ideasPath };
}
function opposite(query) { return `neg(${query})`; }
function runtimeValid(run, condition) {
  const enabled = condition !== "N", expectedTools = enabled ? ["world_memory_query"] : [], names = (run.tools || []).map(x => x?.function?.name);
  const dispatches = run.physical_dispatches, calls = (run.tool_calls || []).length;
  const allowedCalls = condition === "A" ? 2 : (condition === "G" ? 1 : 0), expectedDispatches = calls > 0 ? 2 : 1;
  return run.status === "ok" && run.inference_calls === dispatches && dispatches === expectedDispatches && dispatches >= 1 && dispatches <= (enabled ? 2 : 1) && run.denied_physical_attempts === 0 && run.physical_attempts?.length === dispatches && run.physical_attempts.every(x => ["completed", "closed"].includes(x.status)) && run.provider_terminal_status === "completed" && JSON.stringify(names) === JSON.stringify(expectedTools) && calls <= allowedCalls;
}
function toolScore(run, item, condition) {
  const calls = run.tool_calls || [], parsedReceipts = calls.map(call => { try { return JSON.parse(call.result); } catch { return null; } });
  const primaryIndex = parsedReceipts.findIndex(receipt => receipt?.query === item.formal_world.query), complementIndex = parsedReceipts.findIndex(receipt => receipt?.query === opposite(item.formal_world.query));
  const receipt = primaryIndex >= 0 ? parsedReceipts[primaryIndex] : null;
  const primary_query_called = primaryIndex >= 0, complement_query_called = complementIndex >= 0;
  const query_correct = primary_query_called && calls.every((call, index) => [item.formal_world.query, opposite(item.formal_world.query)].includes(parsedReceipts[index]?.query));
  const receiptSupports = receipt ? supports(receipt, item.formal_world.query) : null;
  const receipt_correct = primary_query_called && receipt.raw_status === item.oracle.status && JSON.stringify(receiptSupports?.positive_support_sets) === JSON.stringify(item.oracle.positive_support_sets) && JSON.stringify(receiptSupports?.negative_support_sets) === JSON.stringify(item.oracle.negative_support_sets);
  return { tool_called: calls.length > 0, tool_call_count: calls.length, primary_query_called, complement_query_called, redundant_second_call: calls.length === 2 && primary_query_called, query_correct, receipt_correct, guided_compliance: condition !== "G" || calls.length === 1 };
}
function score(run, item, condition) {
  const parsed = parseAnswer(run.final_response), runtime_valid = runtimeValid(run, condition), tool = toolScore(run, item, condition), support_set_correct = runtime_valid && parsed.support_shape_valid && JSON.stringify(parsed.positive_support_sets) === JSON.stringify(item.oracle.positive_support_sets) && JSON.stringify(parsed.negative_support_sets) === JSON.stringify(item.oracle.negative_support_sets);
  return { runtime_valid, format_valid: parsed.format_valid, status: parsed.status, expected_status: item.oracle.status, status_correct: runtime_valid && parsed.status === item.oracle.status, support_set_correct, exact: runtime_valid && parsed.format_valid && parsed.status === item.oracle.status && support_set_correct && parsed.canonical_support, ...tool };
}
function makePlan(cases, conditions = CONDITIONS) { const rotations = [["N", "A", "G"], ["A", "G", "N"], ["G", "N", "A"]], plan = []; cases.forEach((item, index) => { const order = rotations[index % 3].filter(x => conditions.includes(x)); for (const condition of order) plan.push({ sequence: plan.length + 1, case: item, condition, order: order.join("→") }); }); return plan; }
function aggregate(records, cases, conditions = CONDITIONS) { const per_condition = {}; for (const condition of conditions) { const rows = records.filter(x => x.condition === condition); per_condition[condition] = { denominator: cases.length, recorded: rows.length, runtime_valid: rows.filter(x => x.score.runtime_valid).length, tool_called: rows.filter(x => x.score.tool_called).length, primary_query_called: rows.filter(x => x.score.primary_query_called).length, complement_query_called: rows.filter(x => x.score.complement_query_called).length, redundant_second_call: rows.filter(x => x.score.redundant_second_call).length, query_correct: rows.filter(x => x.score.query_correct).length, receipt_correct: rows.filter(x => x.score.receipt_correct).length, status_correct: rows.filter(x => x.score.status_correct).length, support_set_correct: rows.filter(x => x.score.support_set_correct).length, exact: rows.filter(x => x.score.exact).length }; } return { per_condition }; }

function runtimeConfig(model) { const adapter = path.join(__dirname, "adapter.py"), info = path.join(ROOT, "world/paired-biographies/runtime_info.py"); const configured = spawnSync(H.PYTHON, [adapter, "--config"], { encoding: "utf8", timeout: 20000, cwd: __dirname }); if (configured.status !== 0) throw new Error(configured.stderr); const probe = spawnSync(H.PYTHON, [info], { encoding: "utf8", timeout: 20000, cwd: path.dirname(info) }); if (probe.status !== 0) throw new Error(probe.stderr); const runtime = JSON.parse(probe.stdout); return { runtime, config: { runtime_fingerprint: runtime.fingerprint, model, provider: "openai-codex", reasoning_effort: "low", max_tokens: 4096, max_iterations: 2, request_timeout_ms: 180000, process_timeout_ms: 360000, retries: 0, fallback: null } }; }
function snapshotSources(out) { const files = ["world/checker.js", "world/checker.pl", "world/journal.js", "world/agent.js", "world/hermes-bridge.js", "integrations/hermes/prolog_world/__init__.py", "world/autonomous-prolog-tool-v5/generator.cjs", "world/autonomous-prolog-tool-v5/collector.cjs", "world/autonomous-prolog-tool-v5/adapter.py", "world/autonomous-prolog-tool-v5/tool_transport_guard.py", "world/autonomous-prolog-tool-v5/verify-report.cjs", "world/paired-biographies/runtime_info.py"]; return files.map(file => { const bytes = fs.readFileSync(path.join(ROOT, file)), target = path.join(out, "source-snapshot", file); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, bytes, { flag: "wx" }); return { file, sha256: H.sha(bytes), snapshot: path.relative(out, target) }; }); }
async function invoke(request, directory, config) {
  fs.mkdirSync(directory, { recursive: true }); const evidencePath = path.join(directory, "adapter.json"), input = { ...request, config, evidence_path: evidencePath, project_root: ROOT, plugin_path: path.join(ROOT, "integrations/hermes/prolog_world") }; exactWrite(path.join(directory, "request.json"), input);
  const processResult = await new Promise(resolve => { const child = spawn(H.PYTHON, [path.join(__dirname, "adapter.py")], { stdio: ["pipe", "pipe", "pipe"], cwd: __dirname }); let stdout = "", stderr = "", reason = null; const timer = setTimeout(() => { reason = "timeout"; child.kill("SIGKILL"); }, config.process_timeout_ms); child.stdout.on("data", x => stdout += x); child.stderr.on("data", x => stderr += x); child.on("error", error => { clearTimeout(timer); resolve({ status: "execution_error", error: error.message }); }); child.on("close", (code, signal) => { clearTimeout(timer); resolve({ status: reason || (code === 0 ? "completed" : "execution_error"), exit_code: code, signal, stdout, stderr }); }); child.stdin.end(JSON.stringify(input)); }); exactWrite(path.join(directory, "process.json"), processResult);
  let evidence = { status: processResult.status, inference_calls: 0, tools: [], tool_calls: [], final_response: "" }; if (fs.existsSync(evidencePath)) try { evidence = JSON.parse(fs.readFileSync(evidencePath)); } catch (error) { evidence.status = "invalid_evidence"; evidence.error = error.message; } if (processResult.status !== "completed") evidence.status = processResult.status; evidence.evidence_sha256 = fs.existsSync(evidencePath) ? H.sha(fs.readFileSync(evidencePath)) : null; return evidence;
}
function options(argv) { const opts = { command: argv[0] || "offline", fixture: DEFAULT_FIXTURE, cases: "all", conditions: [...CONDITIONS], model: null, out: null }; for (let i = 1; i < argv.length; i += 2) { const key = argv[i], value = argv[i + 1]; if (!value || !["--fixture", "--cases", "--conditions", "--model", "--out"].includes(key)) throw new Error("invalid arguments"); opts[key.slice(2)] = value; } opts.fixture = path.resolve(opts.fixture); opts.conditions = typeof opts.conditions === "string" ? opts.conditions.split(",") : opts.conditions; if (!["offline", "live", "resume"].includes(opts.command) || !opts.conditions.length || new Set(opts.conditions).size !== opts.conditions.length || opts.conditions.some(x => !CONDITIONS.includes(x))) throw new Error("invalid command or conditions"); if (["live", "resume"].includes(opts.command) && (!opts.model || !opts.out)) throw new Error("live/resume need model and out"); return opts; }
async function collect({ mode, frozen, model, out, selectedCases, conditions, invokeFn = invoke, runtimeDescriptor = null }) {
  const output = path.resolve(out), reportFile = path.join(output, "report.json"); let report, cases = selectedCases;
  if (mode === "live") { fs.mkdirSync(path.dirname(output), { recursive: true }); fs.mkdirSync(output, { recursive: false }); const { runtime, config } = runtimeDescriptor || runtimeConfig(model); report = { schema_version: "autonomous-prolog-tool-run-v5", status: "running", boundary: "Measures autonomous use of one bounded Prolog query tool on synthetic formal snapshots; system-level tool benefit, not changed model cognition.", fixture: { file: path.relative(ROOT, frozen.file), sha256: frozen.sha256 }, model, config, runtime, selected_cases: cases.map(x => x.case_id), selected_conditions: [...conditions], sources: snapshotSources(output), records: [], summary: null }; exactWrite(reportFile, report); }
  else { report = JSON.parse(fs.readFileSync(reportFile)); if (report.status !== "running" || report.fixture.sha256 !== frozen.sha256 || report.model !== model) throw new Error("resume mismatch"); cases = frozen.fixture.cases.filter(x => report.selected_cases.includes(x.case_id)); conditions = report.selected_conditions; }
  for (const entry of makePlan(cases, conditions)) { if (report.records.some(x => x.case_id === entry.case.case_id && x.condition === entry.condition)) continue; const directory = path.join(output, "calls", entry.case.case_id, entry.condition); let run; if (fs.existsSync(directory)) run = { status: "interrupted", tools: [], tool_calls: [], final_response: "" }; else try { fs.mkdirSync(directory, { recursive: true }); const world = await seedWorld(entry.case, directory); run = await invokeFn({ system: SYSTEM, user: entry.case.prompts[entry.condition.toLowerCase()], tool_enabled: entry.condition !== "N", condition: entry.condition, world }, directory, report.config); } catch (error) { run = { status: "failed", error: error.message, tools: [], tool_calls: [], final_response: "" }; } const scored = score(run, entry.case, entry.condition); report.records.push({ sequence: entry.sequence, case_id: entry.case.case_id, stratum: entry.case.stratum, condition: entry.condition, order: entry.order, status: run.status, score: scored, usage: run.usage || null, evidence: path.relative(output, path.join(directory, "adapter.json")), evidence_sha256: run.evidence_sha256 || null, error: run.error || null }); report.summary = aggregate(report.records, cases, conditions); exactWrite(reportFile, report); console.log(JSON.stringify({ sequence: entry.sequence, case_id: entry.case.case_id, condition: entry.condition, runtime: run.status, tool_called: scored.tool_called, tool_call_count: scored.tool_call_count, query_correct: scored.query_correct, status_correct: scored.status_correct, exact: scored.exact })); }
  report.status = report.records.length === cases.length * conditions.length && report.records.every(x => x.score.runtime_valid) ? "completed" : "completed_with_runtime_failures"; report.summary = aggregate(report.records, cases, conditions); exactWrite(reportFile, report); return report;
}
async function main(argv = process.argv.slice(2)) { const opts = options(argv), frozen = await loadFrozenFixture(opts.fixture), ids = opts.cases === "all" ? frozen.fixture.cases.map(x => x.case_id) : opts.cases.split(","); if (new Set(ids).size !== ids.length || ids.some(id => !frozen.fixture.cases.some(x => x.case_id === id))) throw new Error("unknown/duplicate case"); const cases = frozen.fixture.cases.filter(x => ids.includes(x.case_id)); if (opts.command === "offline") return console.log(JSON.stringify({ status: "ok", cases: cases.length, calls_planned: cases.length * opts.conditions.length, conditions: opts.conditions })); const report = await collect({ mode: opts.command, frozen, model: opts.model, out: opts.out, selectedCases: cases, conditions: opts.conditions }); console.log(JSON.stringify({ out: path.resolve(opts.out), status: report.status, summary: report.summary })); if (report.status !== "completed") process.exitCode = 1; }
if (require.main === module) main().catch(error => { console.error(error.stack || error.message); process.exitCode = 1; });
module.exports = { DEFAULT_FIXTURE, EXPECTED_FIXTURE_SHA256, SYSTEM, aggregate, collect, invoke, loadFrozenFixture, makePlan, runtimeValid, score, seedWorld, snapshotSources, toolScore };
